### ISSUE TITLE
Doesn't work with numpy versions over 1.23.5

### ISSUE THREAD

**Issue by FranzEricSchneider** [knaidoo29/mistree#17]
I was running a library that uses mistree and got the following error about `np.bool` not being available:

```
File /usr/local/lib/python3.8/dist-packages/mistree-1.2.0-py3.8-linux-x86_64.egg/mistree/mst/get_mst_class.py:198, in GetMST.get_branches(self, box_size, sub_divisions)
    187 """Finds the branches of a MST.
    188 
    189 Parameters
   (...)
    195     finding algorithm when using many points (> 100000).
    196 """
    197 if sub_divisions is 1:
--> 198     branch_index, rejected_branch_index = branches.get_branch_index(self.edge_index, self.edge_degree)
    199 else:
    200     if self._mode is '2D':

File /usr/local/lib/python3.8/dist-packages/mistree-1.2.0-py3.8-linux-x86_64.egg/mistree/mst/branches.py:54, in get_branch_index(edge_index, edge_degree, branch_cutting_frequency)
     52 branch_index = []
     53 branch_index_rejected = []
---> 54 mask_end = np.ones(index_branch_end.shape, dtype=np.bool)
     55 mask_mid = np.ones(index_branch_mid.shape, dtype=np.bool)
     56 count = 0

File /usr/local/lib/python3.8/dist-packages/numpy/__init__.py:284, in __getattr__(attr)
    281     from .testing import Tester
    282     return Tester
--> 284 raise AttributeError("module {!r} has no attribute "
    285                      "{!r}".format(__name__, attr))

AttributeError: module 'numpy' has no attribute 'bool'
```

When I did some digging, it looks like numpy 1.24.0+ no longer has that type, and a comment says that 1.23.5 was the last version to have it. I tried doing `pip3 install numpy==1.23.5` and after that the code ran fine.

One solution would be to specify a numpy version in the `requirements.txt` file, but a better one would probably just be to replace `np.bool` with `bool` with a find and replace. According to this numpy warning it's the same thing under the hood:
```
DeprecationWarning: np.bool is a deprecated alias for the builtin bool. To silence this warning, use bool by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use np.bool_ here. Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by knaidoo29** [comment]
Hi @FranzEricSchneider, thanks for pointing this out and thanks for the suggestion! I wasn't aware of this change, I see numpy 1.23.5 was released only last November so this would explain why I haven't come across this before. I'll switch mentions of np.bool to bool shortly so this problem will be fixed soon (i.e. probably this monday)!

**Comment by knaidoo29** [comment]
Apologies about the long wait, this error has now been fixed in the latest version, and available in an update to the pip version.
